#! /bin/bash
echo "--------------------------------Arithmetic Compution And Sorting ----------------------------------"

#TO TAKING INPUT FROM USER
read -p "Enter first input :" a
read -p "Enter second input:" b
read -p "Enter third input :" c


#COMPUTE ARITHMETIC OPERATION
result=`echo "scale=2;$a + $b * $c" | bc`
echo "Result:" $result

#compute operatin 2
resultOne=`echo "scale=2;$a * $b + $c" | bc`
echo "Result:" $resultOne

#compute operation 3
resultTwo=`echo "scale=2;$c + $a / $b " | bc`
echo "Result:" $resultTwo

#commit operation 4
esultThree=`echo "scale=2;$a % $b + $c" | bc`
echo "Result:" $resultThree

#TO STORE THE DICTIONARY
arithmaticOperation[result]=$result
arithmaticOperation[resultOne]=$resultOne
arithmaticOperation[resultTwo]=$resultTwo
arithmaticOperation[resultThree]=$resultThree
